---
title: "Secure Chat Burden at CHOP: Infectious Disease Fellows"
subtitle: "BMIN503/EPID600 Final Project"
author: "Lauren Coogle"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

## Overview {#sec-overview}

For hospitalized children and their families, breakdowns in patient safety can result in long-lasting and costly harm. Communication failure is one of the most common contributors to patient safety events.^1-5^ With the influx of new technology intended to facilitate communication between clinicians, communication workflows are drastically changing.^6^ The Pediatric Patient Safety Learning Laboratory (PSLL) was proposed to reengineer inter-professional communication work systems using a Safety II (or, "resilient healthcare") framework. A multidisciplinary team from Children's Hospital of Philadelphia (CHOP) and the University of Pennsylvania (Penn) was established to enhance the communication work system and prevent harm to hospitalized children. Using systems engineering methodology, specific aims were established for project analysis, design, development, implementation, and evaluation.

At the current stage of this project, we are focused on the first aim: to conduct a problem analysis of the inter-professional communication work system and work processes used in the care of hospitalized children. One work stream focused specifically on secure chat communication. Under the guidance of Dr. Chris Bonafide, Attending Physician at CHOP and Dr. Austin DeChalus, Pediatric Hospital Medicine Fellow at CHOP, I have joined this work stream and used the secure chat data extracted from Epic Clarity to investigate overnight chat burden for infectious disease fellows.

[Link to final project GitHub repository here.](https://github.com/cooglel/BMIN503_Final_Project)

## Introduction {#sec-introduction}

The infectious disease fellows at CHOP have been vocal about their perceived high chat burden on overnight call shifts. Their schedules often had them working during the day, on call that night from home, and then back to work the following day. Inadequate sleep due to interruptive chats was impacting their mental health, and they feared a patient safety event would occur due to inadequate sleep.

In this exploratory data analysis, we sought to characterize secure chats to infectious disease fellows on overnight call shifts. For each evening on weekdays and weekends, a single infectious disease fellow covered call from 5 pm through 7 am. As infectious disease does not admit their own patients, all communication to them would be regarding patients for consult. By characterizing these secure chat messages, we are hoping to design and develop interventions to improve the communication work system. With this baseline analysis, we can then evaluate our interventions in the clinical environment to measure impact of changes.

With the ongoing introduction of technologies that transform how, when, and what clinicians communicate among each other in the inpatient setting, developing infrastructure to proactively evaluate these systems is more important than ever. Clinician-to-clinician communication impacts all hospitalized pediatric patients (around 2.5 million per year) and their family. Our Safety II-informed systems engineering methodology will also be translatable to other systems of care providing a template for the future of patient safety work. The data analysis below is a small but important part of this larger initiative.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.

## References

1.  Hoffman JM, Keeling NJ, Forrest CB, et al. Priorities for pediatric patient safety research. *Pediatrics.* 2019;143(2).
2.  Dixon-Woods M. Why is patient safety so hard? A selective review of ethnographic studies. *J Health Serv Res Policy.* 2010;15:11-16.
3.  Khan A, Furtak SL, Melvin P, Rogers JE, Schuster MA, Landrigan CP. Parent-reported errors and adverse events in hospitalized children. *JAMA Pediatr.* 2016;170(4):e154608.
4.  Leonard M, Graham S, Bonacum D. The human factor: the critical importance of effective teamwork and communication in providing safe care. *Qual Saf Health Care.* 2004;13 Suppl 1:i85-90.
5.  Fortescue EB, Kaushal R, Landrigan CP, et al. Prioritizing strategies for preventing medication errors and adverse drug events in pediatric inpatients. *Pediatrics.* 2003;111:722-729
6.  Hagedorn PA, Singh A, Luo B, Bonafide CP, Simmons JM. Secure text messaging in healthcare: latent threats and opportunities to improve patient safety. *J Hosp Med.* 2020;15(6):378-380.
